REM INSERTING into AME_CALLING_APPS_TL
SET DEFINE OFF;
Insert into AME_CALLING_APPS_TL (APPLICATION_ID,LANGUAGE,SOURCE_LANG,APPLICATION_NAME,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN) values (-421,'AR','US','XXTG Contracts Automation Workflow',12720,to_date('04-APR-17','DD-MON-RR'),12720,to_date('04-APR-17','DD-MON-RR'),0);
Insert into AME_CALLING_APPS_TL (APPLICATION_ID,LANGUAGE,SOURCE_LANG,APPLICATION_NAME,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN) values (-421,'US','US','XXTG Contracts Automation Workflow',12720,to_date('04-APR-17','DD-MON-RR'),12720,to_date('04-APR-17','DD-MON-RR'),0);
