REM INSERTING into AME_CALLING_APPS
SET DEFINE OFF;
Insert into AME_CALLING_APPS (FND_APPLICATION_ID,APPLICATION_NAME,TRANSACTION_TYPE_ID,APPLICATION_ID,LINE_ITEM_ID_QUERY,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,START_DATE,END_DATE,SECURITY_GROUP_ID,OBJECT_VERSION_NUMBER) values (20003,'XXTG Contracts Automation Workflow','XXTGCA',-421,null,12720,to_date('04-APR-17','DD-MON-RR'),12720,to_date('13-JUL-17','DD-MON-RR'),12720,to_date('04-APR-17','DD-MON-RR'),to_date('13-JUL-17','DD-MON-RR'),null,2);
